apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
spec:
  replicas: 1
  selector:  
    matchLabels:
      app: publisher  
  template:
    metadata:
      labels:  
        app: publisher  
    spec:
      containers:
        - name: publisher
          image: publisher
          imagePullPolicy: Never
          volumeMounts:
            - name: config-volume
              mountPath: /publisher
      volumes:
        - name: config-volume
          configMap:
            name: publisher-config

